### PR TITLE
created a profile model on mongoose

### PR DESCRIPTION
**Pull request by prayvakta**
Added a schema for profile and created a model

### CODE REVIEW

**Comment by shawnohn** [comment]
Great works Pray!

If you don't mind, I think it would be better create folder and file for the model for our further works.
e.g) src/model/profileModel.js
We can import to use it anywhere.

The model itself looks good!

**Comment by prayvakta** [comment]
> Great works Pray!
> 
> If you don't mind, I think it would be better create folder and file for the model for our further works.
> e.g) src/model/profileModel.js
> We can import to use it anywhere.
> 
> The model itself looks good!

How about now?

**Comment by shawnohn** [comment]
How about making src folder above models folder?

**Comment by shawnohn** [comment]
Hey Pray!
Never mind my upper comment. Your commit is decent for now!
Sorry for bothering!

**Review by shawnohn — APPROVED** [review]

**Review by shawnohn — APPROVED** [review]

**Pull request merged**
